"""
Agent-13: Günlük Analist (AI-Enhanced)
=======================================
İstatistik verilerini analiz eder, trend tespiti yapar, strateji önerir.
Lokal AI ile akıllı günlük rapor üretimi.
"""

import sys
import os
import datetime

AGENT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(AGENT_DIR)
sys.path.insert(0, SRC_DIR)
sys.path.insert(0, os.path.join(SRC_DIR, "core"))

from core.content_db_lib import ContentDB
from core.config import Config

# AI import – graceful fallback
try:
    from core.llm_local import llm as ai
    AI_OK = ai.is_available()
except Exception:
    ai = None
    AI_OK = False


class AnalystAgent:
    def __init__(self, db: ContentDB):
        self.name = "Agent-13: Daily Analyst (AI)"
        self.db = db

    def generate_daily_report(self):
        print(f"\n--- {self.name} Running ---")
        print(f"    AI Durumu: {'[OK] Qwen2.5 Aktif' if AI_OK else '[!] Fallback (Template)'}")

        # 1. Gather Data
        stats = self.db.get_stats()
        top_tags = self.db.get_top_tags(limit=10)

        # Get recent titles for context
        recent_titles = []
        for status in ['normalized', 'waiting_for_approval', 'new']:
            items = self.db.get_pending_content(limit=10, status=status)
            for item in items:
                recent_titles.append(item['title'])
            if len(recent_titles) >= 10:
                break

        today = datetime.datetime.now().strftime("%Y-%m-%d")
        now_str = datetime.datetime.now().strftime("%d.%m.%Y %H:%M")

        # 2. Generate Report
        if AI_OK:
            try:
                ai_report = ai.generate_daily_report(stats, top_tags, recent_titles)
                if ai_report and len(ai_report) > 100:
                    report = f"""# 📊 Yerel Medya Takip – Günlük AI Rapor ({now_str})

> 🤖 Bu rapor **Qwen2.5 AI** tarafından otomatik üretilmiştir.

## Sistem Özeti
- **Toplam İçerik:** {sum(stats.values())} adet
""" + "\n".join([f"- **{k}:** {v}" for k, v in stats.items()]) + f"""

## En Popüler Konular
""" + "\n".join([f"- **{tag}:** {count} mention" for tag, count in top_tags]) + f"""

---

## 🤖 AI Analiz & Strateji

{ai_report}

---
*Generated by Agent-13 (AI-Enhanced) | {now_str}*
"""
                    print(f"[{self.name}] AI rapor üretildi ({len(ai_report)} char).")
                else:
                    report = self._generate_template_report(stats, top_tags, today, now_str)
            except Exception as e:
                print(f"[{self.name}] AI Error: {e}, falling back to template.")
                report = self._generate_template_report(stats, top_tags, today, now_str)
        else:
            report = self._generate_template_report(stats, top_tags, today, now_str)

        # 3. Save Report
        reports_dir = Config.REPORTS_DIR
        os.makedirs(reports_dir, exist_ok=True)
        filename = f"daily_report_{today}.md"
        filepath = os.path.join(reports_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)

        print(f"[{self.name}] Rapor kaydedildi: {filepath}")

        # Also save a 'latest' version for easy access
        latest_path = os.path.join(reports_dir, "latest_report.md")
        with open(latest_path, "w", encoding="utf-8") as f:
            f.write(report)

        return report

    def _generate_template_report(self, stats, top_tags, today, now_str):
        """Fallback template-based report."""
        report = f"""# 📊 Yerel Medya Takip - Günlük Rapor ({now_str})

## 1. Sistem Özeti
- **İşlenen İçerik**: {sum(stats.values())} adet
- **Onay Bekleyen**: {stats.get('waiting_for_approval', 0)} adet.
- **Yeni İçerik**: {stats.get('new', 0)} adet.
- **Normalize Edilmiş**: {stats.get('normalized', 0)} adet.

## 2. Gündem Analizi (Top Tags)
"""
        for tag, count in top_tags:
            report += f"- **{tag}**: {count} mention\n"

        report += f"""
## 3. Durum
- AI Durumu: {'[OK] Aktif (Qwen2.5)' if AI_OK else '[!] Devre Disi'}
- Son güncelleme: {now_str}

---
*Generated by Agent-13 (Template Mode) | {now_str}*
"""
        return report

    def run(self):
        return self.generate_daily_report()
